title = "CodeStage example"
github = "https://github.com/shi-yan/codestage"
# need to have the slash
prefix = "/codestage"
target = "dist"
utilities = [ "basic_sample",  "basic_sample" ]

[[content]]
title = "1. Basic Sample"
folder = "basic_sample"

[[content.files]]
filename = "index.html"
is_readonly = true

[[content.files]]
filename = "test.js"
is_readonly = true

[[content.files]]
filename = "test.glsl"
is_readonly = true

[[content.sub_chapters]]
title = "1.1 Nested Basic Sample"
folder = "basic_sample"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "1.1.1 Nested Basic Sample"
folder = "basic_sample"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content]]
title = "chapter 2"
folder = "basic_sample"

[[content.files]]
filename = "index.html"
is_readonly = true