title = "WebGPU tutorial"
github = "xxx"

[[content]]
title = "chapter 1"
folder = "test_folder_1"

[[content.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters]]
title = "chapter 1.1"
folder = "test_folder2"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "chapter 1.1.1"
folder = "test_folder2"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content]]
title = "chapter 2"
folder = "test_folder2"
[[content.files]]
filename = "index.html"
is_readonly = true